######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 20 09:30:21 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Mosaic.h SynchronisedQueue.h
FORMS += Mosaic.ui
SOURCES += main.cpp Mosaic.cpp
